spring:
  datasource:
    url: jdbc:h2:mem:testdb;mode=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true

---
spring:
  mvc:
    static-path-pattern: /static/**




