insert into member(id, pwd, member_name, address, telNo, email, member_role, category) values('korea1','1234','고길동','강서구','010-1111-1111','modu@aaa.com','Student','educate')
insert into member(id, pwd, member_name, address, telNo, email, member_role, category) values('korea2','1234','홍길동','강서구','010-1111-1111','modu@aaa.com','Student','sports')
insert into member(id, pwd, member_name, address, telNo, email, member_role, category) values('expert1','1234','백종원','강서구','010-1111-1111','modu@aaa.com','Professor','cook')
insert into member(id, pwd, member_name, address, telNo, email, member_role, category) values('expert2','1234','강형욱','강서구','010-1111-1111','modu@aaa.com','Professor','breeder')
insert into member(id, pwd, member_name, address, telNo, email, member_role, category) values('expert3','1234','오은영','강서구','010-1111-1111','modu@aaa.com','Professor','parenting')
insert into member(id, pwd, member_name, address, telNo, email, member_role, category) values('expert4','1234','강승제','강서구','010-1111-1111','modu@aaa.com','Professor','math')
insert into member(id, pwd, member_name, address, telNo, email, member_role, category) values('korea25','1234','손웅정','강서구','010-1111-1111','modu@aaa.com','Professor','sports')
insert into board(title, writer, content, category, member_seq) values('gg','백종원','안녕하세요','information',2)
